# Generated by Django 2.2.5 on 2019-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('modal_price', models.IntegerField()),
            ],
            options={
                'unique_together': {('arrival_date', 'state', 'district', 'market', 'commodity', 'variety')},
            },
        ),
    ]
