# Generated by Django 2.2.5 on 2019-11-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commodity_data',
            unique_together=set(),
        ),
    ]
