# Generated by Django 2.2.5 on 2019-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20191130_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='distance_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
